cnf(p1,axiom,[pM(b),-pT(t1)]).
cnf(p2,axiom,[pM(b),-pT(t2)]).
cnf(p3,axiom,[pM(c),-pT(t4)]).
cnf(p4,axiom,[pM(a),-pT(t3)]).
cnf(p5,axiom,[pT(t1),-pT(r1),-pT(r2)]).
cnf(p6,axiom,[pT(t2),-pT(r3)]).
cnf(p7,axiom,[pT(t3),-pT(r4),-pT(r5)]).
cnf(p23,axiom,[pT(t4),-pT(r6)]).
cnf(p11,axiom,[pT(r4),-pA(h1)]).
cnf(p12,axiom,[pT(r4),-pA(h2)]).
cnf(p13,axiom,[-pT(r4),-pT(p1)]).
cnf(p8,axiom,[pT(r1),-pT(s1)]).
cnf(p9,axiom,[pT(r2),-pT(s2)]).
cnf(p10,axiom,[pT(r3),-pT(s3),-pT(s4)]).
cnf(p14,axiom,[pT(r5),-pT(s3)]).
cnf(p24,axiom,[pT(r6),-pT(s5)]).
cnf(p15,axiom,[pT(s1),-pA(h1)]).
cnf(p16,axiom,[pT(s2),-pA(h1)]).
cnf(p17,axiom,[pT(s3),-pT(s2)]).
cnf(p18,axiom,[pT(s3),-pT(q1),-pA(h3)]).
cnf(p19,axiom,[pT(s4),-pA(h4)]).
cnf(p25,axiom,[pT(s5),-pA(h1)]).
cnf(p20,axiom,[pT(q1),-pT(p1)]).
cnf(p21,axiom,[pT(p1)]).
cnf(p22,axiom,[-pA(h1),-pA(h3)]).

cnf(d1,top_clause,[-pM(a)]).
cnf(d2,top_clause,[-pM(b)]).
cnf(d3,top_clause,[-pM(c)]).

pf([pM(_)]<2).
